export const TEST_PARKING_LOT_LIST = [{ "id": 1, "name": "Times Square", "address": "1 Matheson Street, Causeway Bay, Hong Kong", "unit_price": 45.0, "capacity": 10, "available_count": 10, "region": "Wan Chai" }, { "id": 2, "name": "New Town Plaza", "address": "New Town Plaza, Sha Tin Centre Street, Sha Tin, Hong Kong", "unit_price": 35.0, "capacity": 20, "available_count": 20, "region": "Sha Tin" }, { "id": 3, "name": "Tai Po Mega Mall", "address": "Tai Po Mega Mall, No.8 & 10 On Pong Road, Tai Po, Hong Kong", "unit_price": 30.0, "capacity": 15, "available_count": 15, "region": "Tai Po" }, { "id": 4, "name": "Langham Place Shopping Mall", "address": "Langham Place Shopping Mall, Shantung Street, Mongkok, Hong Kong", "unit_price": 35.0, "capacity": 10, "available_count": 10, "region": "Yau Tsim Mong" }, { "id": 5, "name": "Stanley Plaza", "address": "Stanley Plaza, 23 Carmel Road, Stanley, Hong Kong", "unit_price": 40.0, "capacity": 10, "available_count": 10, "region": "Southern" }, { "id": 6, "name": "Shatin Park Stage 2 Car Park", "address": "3 Kong Pui St, Sha Tin, Hong Kong", "unit_price": 35.0, "capacity": 10, "available_count": 10, "region": "Sha Tin" }, { "id": 7, "name": "Lippo Sun Plaza carpark", "address": "1 Kowloon Park Dr, Tsim Sha Tsui, Hong Kong", "unit_price": 25.0, "capacity": 20, "available_count": 20, "region": "Yau Tsim Mong" }, { "id": 8, "name": "Ocean Terminal Car Park", "address": "Harbour City, Canton Rd, Tsim Sha Tsui", "unit_price": 35.0, "capacity": 20, "available_count": 20, "region": "Yau Tsim Mong" }, { "id": 9, "name": "HomeSquare Car Park", "address": "Sha Tin Government Offices, 1 Sheung Wo Che Rd, Sha Tin, Hong Kong", "unit_price": 22.0, "capacity": 20, "available_count": 20, "region": "Sha Tin" }, { "id": 10, "name": "Fortune City One Car Park", "address": "1 Ngan Shing St, Sha Tin, Hong Kong", "unit_price": 18.0, "capacity": 10, "available_count": 10, "region": "Sha Tin" }];
export const BACKEND_HOST_URL = "http://hk3cvdv00648.oocl.com:9300";
export const PARKING_LOT_INFO_PATH = "/parking-lots";
export const SORT_BY_NAME = "name";
export const SORT_BY_DISTANCE = "distance";
export const SORT_BY_AVAILABLE = "available";
export const SORT_BY_PRICE = "price";
export const USER_NAME_INIT_STATE = "Register";

